# Generated by Django 5.0.7 on 2026-04-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_id'),
        ('vehicles', '0003_remove_vehicle_created_at_vehicle_assigned_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_collections',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trips',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
