# Generated by Django 6.0.5 on 2026-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unused overpayment credit available to apply to future loans.', max_digits=12),
        ),
    ]
