# Generated by Django 6.0.5 on 2026-06-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='due_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='upcoming_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VehicleMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(default=90, help_text='Number of days between scheduled maintenance services.')),
                ('default_description', models.CharField(blank=True, default='Routine scheduled maintenance', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scheduled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plan', to='vehicles.vehicle')),
            ],
        ),
    ]
