# Generated by Django 5.0.7 on 2026-05-01 08:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('DRIVER', 'Driver Loan'), ('BANK', 'Bank Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
