# Generated by Django 6.0.4 on 2026-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cleared', 'Cleared')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reason',
            field=models.TextField(),
        ),
    ]
