# Generated by Django 5.0.7 on 2026-04-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_rename_loan_date_loan_issued_date_remove_loan_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='ppurpose',
            new_name='purpose',
        ),
    ]
