# Generated by Django 5.0.7 on 2026-04-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_rename_ppurpose_loan_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
