# Generated by Django 5.0.7 on 2026-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0002_alter_maintenanceschedule_id_alter_repairlog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceschedule',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='maintenanceschedule',
            old_name='due_date',
            new_name='service_date',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='repairlog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='repairlog',
            name='repair_date',
        ),
        migrations.RemoveField(
            model_name='repairlog',
            name='repaired_by',
        ),
        migrations.AddField(
            model_name='repairlog',
            name='repaired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repairlog',
            name='issue',
            field=models.TextField(),
        ),
    ]
