# Generated by Django 5.0.7 on 2026-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('MAINTENANCE', 'Maintenance'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
